### ISSUE TITLE
Additional info for add-patient

### ISSUE THREAD

**Issue by dhanushkt** [dhanushkt/alphacare#1]
Additional information is required to be accepted and stored in DB while adding patient:
1. Relative name
2. Relative phone number 
_Get appropriate word for 'relative' as in hospital forms @plnishanth_ 
Required changes in patients DB also should be done.

**Comment by plnishanth** [comment]
Appropriate word for relative??

**Comment by dhanushkt** [comment]
Yes, what word is used to describe them? In hospital form

**Comment by plnishanth** [comment]
Name relative is used in form
