### ISSUE TITLE
Dropdown error in admin/add-staff.php

### ISSUE THREAD

**Issue by plnishanth** [dhanushkt/alphacare#12]
Drop down has select gender as option
![123](https://user-images.githubusercontent.com/36627050/37510428-e952dde0-28f2-11e8-9e8a-ad5e3f437668.JPG)
Drop down has select floor as option
![1212](https://user-images.githubusercontent.com/36627050/37510722-08d3add8-28f4-11e8-9335-602d61e12f1b.JPG)
Mistake in breadcrumbs

**Comment by dhanushkt** [comment]
Phone number validation is not working
