### ISSUE TITLE
Errors in admin/add-doctor.php

### ISSUE THREAD

**Issue by plnishanth** [dhanushkt/alphacare#13]
Spelling mistake in heading 
![1411](https://user-images.githubusercontent.com/36627050/37526650-f305f77e-2955-11e8-8a59-b5e0a2813a55.JPG)

Dropdown error in select gender

Validation for phone number

Doctors specialization should be displayed

**Comment by dhanushkt** [comment]
Doctors specialization should be displayed in view-doctos page
