### ISSUE TITLE
Overlapping of text in edit-patient-profile

### ISSUE THREAD

**Issue by plnishanth** [dhanushkt/alphacare#9]
Email-id is overlapping on mobile number in doctor/edit-patient-profile.php
![capture11](https://user-images.githubusercontent.com/36627050/37049219-41f8cd74-2196-11e8-9361-51f4db2f4ca2.JPG)

**Comment by dhanushkt** [comment]
There should be a horizontal line in between email id and phone

**Comment by dhanushkt** [comment]
Issue is not solved in admin and staff cpanel and after adding ward info changes to edit-patient-profile.php this issue should be refixed
